name: Deploy to ec2

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: "us-east-1"

      - name: Connect to EC2 instance
        uses: appleboy/ssh-action@master
        with:
          hosts: ${{ secrets.EC2_IP_ADDRESS }} 
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/eoserver 
            sudo git fetch origin
            sudo git reset --hard origin/main
            sudo ps aux | grep eoserver | awk '{print $2}' | xargs sudo kill -9
            sudo pkill -f "dotnet run"
            sudo screen -dmS oeserver dotnet run

      - name: Wait for deployment
        run: |
          sleep 30
